config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticate :user do
    resources :posts, only: %i[create destroy index new edit show]
  end

  resources :users do
    resources :posts
  end
  resources :relationships, only: %i[create destroy]
  resources :users do
    member { get :following, :followers }
  end
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user, optional: false
    validates :user_id, presence: true
    validates :title, presence: true, length: { maximum: 30 }
    validates :content, presence: true, length: { maximum: 140 }
    default_scope -> { order(created_at: :desc) }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, uniqueness: true
  validates :email,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
            }
  has_many :posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
           foreign_key: 'follower_id',
           dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: 'Relationship',
           foreign_key: 'followed_id',
           dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  # helper_methods

  def follow(other)
    active_relationships.create(followed_id: other.id)
  end

  def unfollow(other)
    active_relationships.find_by(followed_id: other.id).destroy
  end

  def following?(other)
    following.include?(other)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    attributes = [:name, :email]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!

    def index
      @posts = current_user.posts.all
    end

    def show
        @post = Post.find(params[:id])
    end

    def new
        @post = Post.new
    end

    def create
      @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to current_user, notice: 'Post was successfully created.' }
      else
        format.html { render :new }
      end
    end
    end

    private

    def set_post
        @post = Post.find(params[:id])
    end

    def post_params
        params.require(:post).permit(:title, :content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @users = @user.following
    render 'users/follow_show'
  end

  def followers
    @title = 'Followers'
    @user = User.find(params[:id])
    @users = @user.followers
    render 'follow_show'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="column column-right">
<section class="hero">
  <div class="hero-body">
    <div class="container">
      <img src="https://upload.wikimedia.org/wikipedia/commons/b/b1/Rockstar_Games_Social_Club_Logo.png">
    </div>
  </div>
</section>
</div>

app/views/layouts/_header.html.erb
<div class="column is-one-quarter">
<ul class="menu-list">
<% if user_signed_in? %>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'New Post', new_post_path(user_id: current_user.id)%></li>
    <li><%= link_to 'My account', current_user%></li>
    <li><%= link_to "Log out", destroy_user_session_path, method: :delete%></li>
    <% else %>
    <li><%= link_to "Sign in", new_user_session_path%></li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social-app</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
  <div class="columns">
    <%= render 'layouts/header'%>
    <%= yield %>
  </div>
  </div>
  </body>

</html>

app/views/posts/_form.html.erb
<div class="column mt-3">
<%= form_with(model: post, local: true) do |form| %>
<h4>Title:</h4>
<%= form.text_area :title , placeholder:"Title.." , class: 'input mb-3'%>
    <h4>Content:</h4>
<%= form.text_area :content , placeholder:"Your content.." , class: 'input mb-3' %>

<%= form.submit "Upload", class: 'button is-primary' %>

<% end %>
</div><div class="column"></div>

app/views/posts/index.html.erb
<h4>Posts</h4>

<% @posts.each do |post| %>

<%= post.title %>

<%= post.description %>

<%= link_to post.title, title %>

<%= end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h5><%= @post.content%></h5>

app/views/users/_follow_form.html.erb
<% if current_user.id != @user.id %>
  <div>
    <% if !current_user.following?(@user) %>

      <%= form_for(current_user.active_relationships.build) do |f| %>
        <div><%= hidden_field_tag :followed_id, @user.id %></div>
        <%= f.submit "Follow", class: "button is-success" %>
      <% end %>

    <% else %>

      <%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
                   html: { method: :delete }) do |f| %>
        <%= f.submit "Unfollow", class:"button is-danger" %>
      <% end %>

    <% end %>
  </div>
<% end %>

app/views/users/_follow_stats.html.erb
<% @user ||= current_user %>

<div class="mb-2">
  <a href=" <%= following_user_path(@user) %>" class="button is-light" >
    <strong class="mr-1">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>" class="button is-light">
    <strong class="mr-1">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/follow_show.html.erb
<section class="section users">
  <h1 class="title is-capitalized"><%= @title %></h1>
  <hr />
<% @users.each do |user| %>
    <h2 class="title is-capitalized">
      <%= link_to user.name, user %>
    </h2>
    <h3 class="subtitle is-lowercase">
      <%= user.email%>
    </h3>
    <hr>
<% end %>
</section>

app/views/users/index.html.erb
<section class="section users">
  <h1 class="title is-capitalized"><%= pluralize(@users.count, "User") %></h1>
  <hr />
<% @users.each do |user| %>
        <h2 class="title is-capitalized">
          <%= link_to user.name, user %>
          <% if user.id == current_user.id%>
            <small class="subtitle">(You)</small>
          <% end %>
        </h2>
        <h3 class="subtitle is-lowercase">
          <%= user.email%>
        </h3>
    <hr>
<% end %>
</section>

app/views/users/show.html.erb
<div class="column">
<section class="hero is-dark ">
  <div class="hero-body ">
    <div class="container">
      <h1 class="title is-capitalized">
        <%= @user.name %>
      </h1>
      <h2 class="subtitle is-lowercase">
        <%= @user.email%>
      </h2>
      <%= render 'follow_stats' %>
      <%= render 'follow_form' if user_signed_in? %>
    </div>
  </div>
</section>
<br />
  <p class="notice has-text-success"><%= flash[:notice] %></p>
<% @user.posts.each do |post| %>
    <div class="columns">
      <div class="column">
        <h1 class="title"><%= post.title %></h1>
        <h2 class="subtitle"><%= post.content %>
        </h2>
      </div>
    <div class="column">
  <div class="has-text-right"><small>Posted <%= time_ago_in_words(post.created_at) %> ago</small>
  </div>
    </div>
  </div>
<% end %>   
</div>